package com.hareeshvar.attendance.enums;

public enum AuditAction {
    // User actions
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    ROLE_CHANGED,
    USER_STATUS_CHANGED,

    // Department actions
    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_DELETED,

    // Designation actions
    DESIGNATION_CREATED,
    DESIGNATION_UPDATED,
    DESIGNATION_DELETED,

    // Shift actions
    SHIFT_CREATED,
    SHIFT_UPDATED,
    SHIFT_DELETED,
    SHIFT_ASSIGNED,

    // Attendance actions
    ATTENDANCE_CHECK_IN,
    ATTENDANCE_CHECK_OUT,
    ATTENDANCE_UPDATED,
    ATTENDANCE_DELETED,

    // Leave actions
    LEAVE_CREATED,
    LEAVE_UPDATED,
    LEAVE_CANCELLED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,

    // Payroll actions
    PAYROLL_CREATED,
    PAYROLL_UPDATED,
    PAYROLL_DELETED,

    // Report actions
    REPORT_GENERATED,

    // Workplace actions
    WORKPLACE_CREATED,
    WORKPLACE_UPDATED,
    WORKPLACE_ACTIVATED,
    WORKPLACE_DEACTIVATED,
    WORKPLACE_DELETED,
    WORKPLACE_ASSIGNED,

    // Geofence & Location verification actions
    GEOFENCE_VERIFICATION_SUCCESS,
    GEOFENCE_VERIFICATION_FAILED,
    LOCATION_ACCURACY_REJECTED,
    ADMIN_ATTENDANCE_OVERRIDE,

    // Authentication & Security actions
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    TOKEN_REFRESH,
    TOKEN_REUSE_DETECTED,
    SESSION_REVOKED,
    ACCESS_DENIED
}
