package com.hareeshvar.attendance.exception;

public enum ErrorCode {
    VALIDATION_FAILED,
    MALFORMED_JSON,
    BAD_REQUEST,
    UNAUTHORIZED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    RESOURCE_ALREADY_EXISTS,
    CONFLICT,
    DATA_INTEGRITY_VIOLATION,
    BUSINESS_RULE_VIOLATION,
    INTERNAL_SERVER_ERROR
}
